Dictionary = {
    "ModelVersion": None,
    "OrganizationCode": None,
    "DictionaryCode": None,
    "DictionaryVersion": None,
    "DictionaryName": None,
    "ReleaseDate": None,
    "Status": None,
    "MoreInfoUrl": None,
    "UseOwnUri": False,
    "DictionaryUri": None,
    "LanguageIsoCode": None,
    "LanguageOnly": False,
    "License": None,
    "LicenseUrl": None,
    "QualityAssuranceProcedure": None,
    "QualityAssuranceProcedureUrl": None,
    "Classes": [],
    "Properties": []
}

Class = {
    "Code": None,
    "Uid": None,
    "OwnedUri": None,
    "Name": None,
    "Definition": None,
    "Status": None,
    "ActivationDateUtc": "2022-05-12T00:00:00+02:00",
    "RevisionDateUtc": None,
    "VersionDateUtc": "2022-05-12T00:00:00+02:00",
    "DeActivationDateUtc": None,
    "VersionNumber": None,
    "RevisionNumber": None,
    "ReplacedObjectCodes": [],
    "ReplacingObjectCodes": [],
    "DeprecationExplanation": None,
    "CreatorLanguageIsoCode": None,
    "VisualRepresentationUri": None,
    "CountriesOfUse": [],
    "SubdivisionsOfUse": [],
    "CountryOfOrigin": None,
    "DocumentReference": None,
    "Synonyms": [],
    "ReferenceCode": None,
    "ClassRelations": [],
    "ClassType": None,
    "ParentClassCode": None,
    "RelatedIfcEntityNamesList": [],
    "ClassProperties": []
    }

ClassRelation = {
    "(Origin Class Code)": None,
    "RelationType": None,
    "RelatedClassUri": None,
    "RelatedClassName": None,
    "Fraction": None
    }

AllowedValue = {
    "(Origin Property Code)": None,
    "(ClassProperty Code)": None,
    "Uri": None,
    "Code": None,
    "Value": None,
    "Description": None,
    "SortNumber": None
    }

ClassProperty = {
    "(Origin Class Code)": None,
    "AllowedValues": [],
    "Code": None,
    "Description": None,
    "IsRequired": None,
    "IsWritable": None,
    "MaxExclusive": None,
    "MaxInclusive": None,
    "MinExclusive": None,
    "MinInclusive": None,
    "Pattern": None,
    "PredefinedValue": None,
    "PropertyCode": None,
    "PropertyUri": None,
    "PropertySet": None,
    "PropertyType": None,
    "SortNumber": None,
    "Symbol": None,
    "Unit": None
    }

Property = {
    "Code": None,
    "Uid": None,
    "OwnedUri": None,
    "Name": None,
    "Definition": None,
    "Status": None,
    "ActivationDateUtc": "2022-05-12T00:00:00+02:00",
    "RevisionDateUtc": None,
    "VersionDateUtc": "2022-05-12T00:00:00+02:00",
    "DeActivationDateUtc": None,
    "VersionNumber": None,
    "RevisionNumber": None,
    "ReplacedObjectCodes": [],
    "ReplacingObjectCodes": [],
    "DeprecationExplanation": None,
    "CreatorLanguageIsoCode": None,
    "VisualRepresentationUri": None,
    "CountriesOfUse": [],
    "SubdivisionsOfUse": [],
    "CountryOfOrigin": None,
    "DocumentReference": None,
    "Description": None,
    "Example": None,
    "ConnectedPropertyCodes": [],
    "PhysicalQuantity": None,
    "Dimension": None,
    "DimensionLength": None,
    "DimensionMass": None,
    "DimensionTime": None,
    "DimensionElectricCurrent": None,
    "DimensionThermodynamicTemperature": None,
    "DimensionAmountOfSubstance": None,
    "DimensionLuminousIntensity": None,
    "MethodOfMeasurement": None,
    "DataType": None,
    "PropertyValueKind": None,
    "MinInclusive": None,
    "MaxInclusive": None,
    "MinExclusive": None,
    "MaxExclusive": None,
    "Pattern": None,
    "IsDynamic": False,
    "DynamicParameterPropertyCodes": [],
    "Units": [],
    "AllowedValues": [],
    "TextFormat": None,
    "PropertyRelations": []
    }

PropertyRelation = {
    "(Origin Property)": None,
    "RelationType": None,
    "RelatedPropertyUri": None,
    "RelatedPropertyName": None
    }
