Domain = {
    "OrganizationCode": None,
    "DomainCode": None,
    "DomainVersion": None,
    "DomainName": None,
    "ReleaseDate": None,
    "Status": None,
    "MoreInfoUrl": None,
    "UseOwnUri": False,
    "DomainNamespaceUri": None,
    "LanguageIsoCode": None,
    "LanguageOnly": False,
    "License": None,
    "LicenseUrl": None,
    "QualityAssuranceProcedure": None,
    "QualityAssuranceProcedureUrl": None,
    "Classifications": [],
    "Properties": [],
    "Materials": []
}

Classification = {
    "Code": None,
    "Uid": None,
    "OwnedUri": None,
    "Name": None,
    "Definition": None,
    "Status": None,
    "ActivationDateUtc": "2022-05-12T00:00:00+02:00",
    "RevisionDateUtc": None,
    "VersionDateUtc": "2022-05-12T00:00:00+02:00",
    "DeActivationDateUtc": None,
    "VersionNumber": None,
    "RevisionNumber": None,
    "ReplacedObjectCodes": [],
    "ReplacingObjectCodes": [],
    "DeprecationExplanation": None,
    "CreatorLanguageIsoCode": None,
    "VisualRepresentationUri": None,
    "CountriesOfUse": [],
    "SubdivisionsOfUse": [],
    "CountryOfOrigin": None,
    "DocumentReference": None,
    "Synonyms": [],
    "ReferenceCode": None,
    "ClassificationRelations": [],
    "ClassificationType": None,
    "ParentClassificationCode": None,
    "RelatedIfcEntityNamesList": [],
    "ClassificationProperties": []
    }

ClassificationRelation = {
    "(Origin Classification Code)": None,
    "RelationType": None,
    "RelatedClassificationUri": None,
    "RelatedClassificationName": None,
    "Fraction": None
    }

AllowedValue = {
    "(Origin Property Code OR ClassificationProperty Code)": None,
    "NamespaceUri": None,
    "Code": None,
    "Value": None,
    "Description": None,
    "SortNumber": None
    }

ClassificationProperty = {
    "(Origin Classification Code)": None,
    "AllowedValues": [],
    "Code": None,
    "Description": None,
    "IsRequired": None,
    "IsWritable": None,
    "MaxExclusive": None,
    "MaxInclusive": None,
    "MinExclusive": None,
    "MinInclusive": None,
    "Pattern": None,
    "PredefinedValue": None,
    "PropertyCode": None,
    "PropertyNamespaceUri": None,
    "PropertySet": None,
    "PropertyType": None,
    "SortNumber": None,
    "Symbol": None,
    "Unit": None
    }

Property = {
    "Code": None,
    "Uid": None,
    "OwnedUri": None,
    "Name": None,
    "Definition": None,
    "Status": None,
    "ActivationDateUtc": "2022-05-12T00:00:00+02:00",
    "RevisionDateUtc": None,
    "VersionDateUtc": "2022-05-12T00:00:00+02:00",
    "DeActivationDateUtc": None,
    "VersionNumber": None,
    "RevisionNumber": None,
    "ReplacedObjectCodes": [],
    "ReplacingObjectCodes": [],
    "DeprecationExplanation": None,
    "CreatorLanguageIsoCode": None,
    "VisualRepresentationUri": None,
    "CountriesOfUse": [],
    "SubdivisionsOfUse": [],
    "CountryOfOrigin": None,
    "DocumentReference": None,
    "Description": None,
    "Example": None,
    "ConnectedPropertyCodes": [],
    "PhysicalQuantity": None,
    "Dimension": None,
    "DimensionLength": None,
    "DimensionMass": None,
    "DimensionTime": None,
    "DimensionElectricCurrent": None,
    "DimensionThermodynamicTemperature": None,
    "DimensionAmountOfSubstance": None,
    "DimensionLuminousIntensity": None,
    "MethodOfMeasurement": None,
    "DataType": None,
    "PropertyValueKind": None,
    "MinInclusive": None,
    "MaxInclusive": None,
    "MinExclusive": None,
    "MaxExclusive": None,
    "Pattern": None,
    "IsDynamic": False,
    "DynamicParameterPropertyCodes": [],
    "Units": [],
    "AllowedValues": [],
    "TextFormat": None,
    "PropertyRelations": []
    }

PropertyRelation = {
    "(Origin Property)": None,
    "RelationType": None,
    "RelatedPropertyUri": None,
    "RelatedPropertyName": None
    }

Material = {
    "Code": None,
    "Uid": None,
    "OwnedUri": None,
    "Name": None,
    "Definition": None,
    "Status": None,
    "DeactivationDateUtc": None,
    "ActivationDateUtc": "2022-05-12T00:00:00+02:00",
    "RevisionDateUtc": None,
    "VersionDateUtc": "2022-05-12T00:00:00+02:00",
    "DeActivationDateUtc": None,
    "VersionNumber": None,
    "RevisionNumber": None,
    "ReplacedObjectCodes": [],
    "ReplacingObjectCodes": [],
    "DeprecationExplanation": None,
    "CreatorLanguageIsoCode": None,
    "VisualRepresentationUri": None,
    "CountriesOfUse": [],
    "SubdivisionsOfUse": [],
    "CountryOfOrigin": None,
    "DocumentReference": None,
    "Synonyms": [],
    "ReferenceCode": None,
    "ClassificationRelations": [],
    "ParentMaterialCode": None,
    "MaterialProperties": []
    }