{
  "OrganizationCode": "buildingsmart",
  "DomainCode": "ifc",
  "DomainVersion": "4.3",
  "DomainName": "IFC",
  "ReleaseDate": "2016-01-01",
  "LanguageIsoCode": "EN",
  "LanguageOnly": false,
  "License": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International",
  "LicenseUrl": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
  "Status": "Released",
  "QualityAssuranceProcedure": "bSI process",
  "QualityAssuranceProcedureUrl": "https://www.buildingsmart.org/about/bsi-process",
  "Classifications": [
    {
      "Code": "ifcwall",
      "Name": "IfcWall",
      "Definition": "The wall represents a vertical construction that may bound or subdivide spaces. Wall are usually vertical, or nearly vertical, planar elements, often designed to bear structural loads. A wall is however S not required to be load bearing. .extDef NOTE Definition according to ISO 6707 1 vertical construction usually in masonry or in concrete which bounds or subdivides a construction works and fulfils a load bearing or retaining function. NOTE There is a representation of walls for structural analysis provided by a proper subtype of IfcStructuralMember being part of the IfcStructuralAnalysisModel . NOTE An arbitrary planar element to which this semantic information is not applicable is not predominantly vertical , shall be modeled as IfcPlate . A wall may have openings, such as wall openings, openings used for windows or doors, or niches and recesses. They are defined by an IfcOpeningElement attached to the wall using the inverse relationship HasOpenings pointing to IfcRelVoidsElement . NOTE Walls with openings that have already been modeled within the enclosing geometry may use the relationship IfcRelConnectsElements to associate the wall with embedded elements such as doors and windows. There are three entities for wall occurrences IfcWallStandardCase S used for all occurrences of walls, that have a non changing thickness along the wall path and where the thickness parameter can be fully described by a material layer set. These walls are always represented geometrically by an Axis and a SweptSolid shape representation or by a Clipping geometry based on SweptSolid , if a 3D geometric representation is assigned. In addition they have to have a corresponding IfcMaterialProfileSetUsage assigned. IfcWallElementedCase used for occurrences of walls which are aggregated from subordinate elements, following specific decomposition rules expressed by the mandatory use of IfcRelAggregates relationship. IfcWall S used for all other occurrences of wall, particularly for walls with changing thickness along the wall path e.g. polygonal walls , or walls with a non rectangular cross sections e.g. L shaped retaining walls , and walls having an extrusion axis that is unequal to the global Z axis of the project i.e. non vertical walls , or walls having only Brep , or SurfaceModel geometry. HISTORY New entity in IFC1.0 bSI Documentation",
      "Status": "Active",
      "ActivationDateUtc": "2010-09-08",
      "VersionDateUtc": "2001-01-01T00:00:00",
      "Synonyms": [],
      "ClassificationRelations": [
        {
          "RelationType": "IsEqualTo",
          "RelatedClassificationUri": "abcd"
        }
      ],
      "ClassificationProperties": [
        {
          "Code": "",
          "PropertyCode": "prop1",
          "ExternalPropertyUri": "",
          "Unit": "",
          "SortNumber": null,
          "Symbol": "",
          "PropertyType": "Property",
          "PropertySet": "",
          "PredefinedValue": "",
          "MinExclusive": null,
          "MaxExclusive": null,
          "Values": []
        }
      ]
    },
    {
      "Code": "class2",
      "Name": "Class 2",
      "Definition": "",
      "Status": "Active",
      "ActivationDateUtc": "2001-01-01T00:00:00",
      "RevisionDateUtc": null,
      "VersionDateUtc": "2001-01-01T00:00:00",
      "DeActivationDateUtc": null,
      "VersionNumber": null,
      "RevisionNumber": null,
      "ReplacedObjectCodes": [],
      "ReplacingObjectCodes": [],
      "DeprecationExplanation": "",
      "CreatorLanguageIsoCode": "",
      "VisualRepresentationUri": "",
      "CountriesOfUse": [],
      "SubdivisionsOfUse": [],
      "CountryOfOrigin": "NL",
      "DocumentReference": "",
      "ClassificationType": "Class",
      "ParentClassificationCode": "class1",
      "RelatedIfcEntityNamesList": [],
      "Synonyms": [],
      "ClassificationRelations": null,
      "ClassificationProperties": [
        {
          "Code": "",
          "PropertyCode": "prop2",
          "ExternalPropertyUri": "",
          "Unit": "mm",
          "SortNumber": null,
          "Symbol": "",
          "PropertyType": "Property",
          "PropertySet": "",
          "PredefinedValue": "",
          "MinInclusive": null,
          "MaxInclusive": null,
          "Values": []
        }
      ]
    }
  ],
  "Properties": [
    {
      "Code": "prop1",
      "Name": "Property 1",
      "Definition": "Some definition",
      "Status": "Active",
      "ActivationDateUtc": "2001-01-01T00:00:00",
      "RevisionDateUtc": null,
      "VersionDateUtc": "2001-01-01T00:00:00",
      "DeActivationDateUtc": null,
      "VersionNumber": 1,
      "RevisionNumber": 0,
      "ReplacedObjectCodes": [ "abc", "def" ],
      "ReplacingObjectCodes": [ "ghi", "jkl" ],
      "DeprecationExplanation": "Deprecated",
      "CreatorLanguageIsoCode": "nl-NL",
      "VisualRepresentationUri": null,
      "CountriesOfUse": [ "GB", "NL" ],
      "SubdivisionsOfUse": [ "NH" ],
      "CountryOfOrigin": "NL",
      "DocumentReference": "EN 196-3:2016",
      "Description": "Property description",
      "Example": "Example 1",
      "ConnectedPropertyCodes": [],
      "PhysicalQuantity": "",
      "Dimension": "",
      "DimensionMass": 2,
      "DimensionTime": -1,
      "MethodOfMeasurement": "",
      "DataType": "String",
      "Pattern": "[a-z",
      "IsDynamic": false,
      "DynamicParameterPropertyCodes": [],
      "Units": [ "mm", "cm" ],
      "AllowedValues": [],
      "TextFormat": ""
    },
    {
      "Code": "prop2",
      "Name": "Property 2",
      "Definition": "",
      "Status": "Active",
      "ActivationDateUtc": "2001-01-01T00:00:00",
      "RevisionDateUtc": null,
      "VersionDateUtc": "2001-01-01T00:00:00",
      "DeActivationDateUtc": null,
      "VersionNumber": null,
      "RevisionNumber": null,
      "ReplacedObjectCodes": [],
      "ReplacingObjectCodes": [],
      "DeprecationExplanation": "",
      "CreatorLanguageIsoCode": "",
      "VisualRepresentationUri": "",
      "CountriesOfUse": [],
      "SubdivisionsOfUse": [],
      "CountryOfOrigin": "",
      "DocumentReference": "",
      "Description": "",
      "Example": "",
      "ConnectedPropertyCodes": [],
      "PhysicalQuantity": "",
      "Dimension": null,
      "DimensionLength": -1,
      "DimensionMass": 2,
      "DimensionTime": 0,
      "DimensionElectricCurrent": 0,
      "DimensionThermodynamicTemperature": 0,
      "DimensionAmountOfSubstance": 0,
      "DimensionLuminousIntensity": 0,
      "MethodOfMeasurement": "",
      "DataType": "Integer",
      "IsDynamic": false,
      "DynamicParameterPropertyCodes": [],
      "Units": [],
      "AllowedValues": [],
      "TextFormat": ""
    }
  ]
}