# bSDD - IFC mapping

How to map bSDD data into IFC (in different versions of IFC)

|                                  | bSDD                                                                                         |  | IFC 4.3                                   |  | IFC 4                                     |  | IFC 2x3                                  |
| -------------------------------- | -------------------------------------------------------------------------------------------- |  | ----------------------------------------- |  | ----------------------------------------- |  | ---------------------------------------- |
| PROPERTIES                       |                                                                                              |  |                                           |  |                                           |  |                                          |
| Property name                    | name (of the property)                                                                       |  | IfcProperty.Name                          |  | IfcProperty.Name                          |  | IfcProperty.Name                         |
| Property value                   | predefinedValue (of the property)                                                            |  | IfcPropertySingleValue.NominalValue       |  | IfcPropertySingleValue.NominalValue       |  | IfcPropertySingleValue.NominalValue      |
| Property source                  | propertyNamespaceUri                                                                         |  | IfcProperty.Specification                 |  | IfcProperty.Description                   |  | IfcProperty.Description                  |
| PropertySet name                 | propertySet                                                                                  |  | IfcPropertySet.Name                       |  | IfcPropertySet.Name                       |  | IfcPropertySet.Name                      |
| CLASSES/CLASSIFICATIONREFERENCES |                                                                                              |  |                                           |  |                                           |  |
| Classification name              | name (of the classification)                                                                 |  | IfcClassificationReference.Name           |  | IfcClassificationReference.Name           |  | IfcClassificationReference.Name          |
| Classification value             | ReferenceCode (optional in bSDD)                                                             |  | IfcClassificationReference.Identification |  | IfcClassificationReference.Identification |  | IfcClassificationReference.ItemReference |
| Classification source            | namespaceUri of the classification                                                           |  | IfcClassificationReference.Location       |  | IfcClassificationReference.Location       |  | IfcClassificationReference.Location      |
| DOMAINS/CLASSIFICATIONSYSTEMS    |                                                                                              |  |                                           |  |                                           |  |
| Domain name                      | name (of the domain)                                                                         |  | IfcClassification.Name                    |  | IfcClassification.Name                    |  | IfcClassification.Name                   |
| Domain source                    | namespaceUri of the domain                                                                   |  | IfcClassification.Specification           |  | IfcClassification.Location                |  | \-                                       |
| Domain version                   | version (of the domain)                                                                      |  | IfcClassification.Edition                 |  | IfcClassification.Edition                 |  | IfcClassification.Edition                |
| Domain owner                     | organizationNameOwner                                                                        |  | IfcClassification.Source                  |  | IfcClassification.Source                  |  | IfcClassification.Source                 |
| Domain date                      | ReleaseDate (of the domain)                                                                  |  | IfcClassification.EditionDate             |  | IfcClassification.EditionDate             |  | IfcClassification.EditionDate            |
| MATERIALS                        |                                                                                              |  |                                           |  |                                           |  |                                          |
| Material name/value              | (for classificationType: "Material") ReferenceCode                                           |  | IfcMaterial.Name                          |  | IfcMaterial.Name                          |  | IfcMaterial.Name                         |
| Material source                  | (for classificationType: "Material")  namespaceUri                                           |  | IfcMaterial.Description                   |  | IfcMaterial.Description                   |  | IfcMaterial.Description                  |
| ATTRIBUTES                       |                                                                                              |  |                                           |  |                                           |  |                                          |
| Attribute name                   | name' of property of which 'PropertySet' value is 'attribute'                                |  | n.a. --> already in IFC                   |  | n.a. --> already in IFC                   |  | n.a. --> already in IFC                  |
| Attribute value                  | predefinedValue; or possibleValues (of property of which 'PropertySet' value is 'attribute') |  | n.a. --> already in IFC                   |  | n.a. --> already in IFC                   |  | n.a. --> already in IFC                  |
